auth:
  type: DISABLED
kafka:
  clusters:
  - bootstrapServers: kafka:29092
    kafkaConnect:
    - address: http://kafka-connect:8083
      name: connect
    name: local-kafka-cluster
    properties: {}
    readOnly: false
    schemaRegistry: http://schema-registry:8085
rbac:
  roles: []
webclient: {}
