### Register MySQL JSON Source Connector
POST http://localhost:28083/connectors
Content-Type: application/json

< ./mysql-json-source-connector.json

### Register MySQL Avro Source Connector
POST http://localhost:28083/connectors
Content-Type: application/json

< ./mysql-avro-source-connector.json

### Register MongoDB JSON Sink Connector
POST http://localhost:28083/connectors
Content-Type: application/json

< ./mongo-json-sink-connector.json

### Register MongoDB Avro Sink Connector
POST http://localhost:28083/connectors
Content-Type: application/json

< ./mongo-avro-sink-connector.json
